server:
  port: 8761
  servlet:
    context-path: /eureka
spring:
  application:
    name: DISCOVERY-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
